version: "3.7"

services:
  backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      - spring.datasource.username=${POSTGRES_USER}
      - spring.datasource.password=${POSTGRES_PASSWORD}
    depends_on:
      - postgres

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - PGDATA=/var/lib/postgresql/data/pgdata
      - LANG=de_DE.utf8
      - POSTGRES_INITDB_ARGS=--locale-provider=icu --icu-locale=de-DE
    ports:
      - "5432:5432"

  #simple db admin for postgres
  adminer:
    image: adminer
    restart: always
    ports:
      - "8090:8080"